version: '3.8'

services:
  web:
    build: ./web/
    env_file:
      - .env
    ports:
      - 180:8080
    volumes:
      - ./web:/usr/src/app/web
    command: air ./app/main.go -b 0.0.0.0
  backend:
    build: ./backend/
    ports:
      - 181:8080
    volumes:
      - ./backend:/usr/src/app/backend
    command: air ./app/main.go -b 0.0.0.0
