version: '3.8'

services:
  web:
    build: ./web/
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./web:/usr/src/app/web
    command: air ./app/main.go -b 0.0.0.0
  orchestrator:
    build: ./orchestrator
    env_file:
      - .env
    ports:
      - 81:81
    volumes:
      - ./orchestrator:/usr/src/app/orchestrator
    command: air ./main.go -b 0.0.0.0
  calculator:
    build: ./calculator
    ports:
      - 85:85
    volumes:
      - ./calculator:/usr/src/app/calculator
    command: air ./main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/usr/src/app/postgresql/data

volumes:
  postgres-db: